USE [master]
GO
/****** Object:  Database [ClientDB]    Script Date: 2024/08/01 04:59:21 PM ******/
CREATE DATABASE [ClientDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClientDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ClientDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClientDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Log\ClientDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ClientDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClientDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ClientDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClientDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClientDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClientDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClientDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClientDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ClientDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClientDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClientDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClientDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClientDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClientDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClientDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClientDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClientDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClientDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClientDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClientDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClientDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClientDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClientDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ClientDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ClientDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ClientDB] SET  MULTI_USER 
GO
ALTER DATABASE [ClientDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClientDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ClientDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ClientDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ClientDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ClientDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ClientDB] SET QUERY_STORE = OFF
GO
USE [ClientDB]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 2024/08/01 04:59:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[ClientId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[ResidentialAddress] [varchar](50) NULL,
	[WorkAddress] [varchar](50) NULL,
	[PostalAddress] [varchar](50) NULL,
	[CellNumber] [varchar](50) NULL,
	[WorkNumber] [varchar](50) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ClientDB] SET  READ_WRITE 
GO
